// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Gy0FgYlG3nCFrxYCflp1VymB8uSuFxQ',
    appId: '1:263376026617:web:d3edb30fdf483911fa1b28',
    messagingSenderId: '263376026617',
    projectId: 'spotify-010',
    authDomain: 'spotify-010.firebaseapp.com',
    storageBucket: 'spotify-010.appspot.com',
    measurementId: 'G-BY85ZBHJJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0OcUuVYia8pBe3jYfwAnWgJ2wqQvdzVE',
    appId: '1:263376026617:android:faafe508435e3ac8fa1b28',
    messagingSenderId: '263376026617',
    projectId: 'spotify-010',
    storageBucket: 'spotify-010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5qq662Yh9vbfgnOBvl5irTgTsorczv6k',
    appId: '1:263376026617:ios:f55190221e0f13e7fa1b28',
    messagingSenderId: '263376026617',
    projectId: 'spotify-010',
    storageBucket: 'spotify-010.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5qq662Yh9vbfgnOBvl5irTgTsorczv6k',
    appId: '1:263376026617:ios:f55190221e0f13e7fa1b28',
    messagingSenderId: '263376026617',
    projectId: 'spotify-010',
    storageBucket: 'spotify-010.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Gy0FgYlG3nCFrxYCflp1VymB8uSuFxQ',
    appId: '1:263376026617:web:b92ab502da392651fa1b28',
    messagingSenderId: '263376026617',
    projectId: 'spotify-010',
    authDomain: 'spotify-010.firebaseapp.com',
    storageBucket: 'spotify-010.appspot.com',
    measurementId: 'G-61FH8PBCNG',
  );
}
